-- ====================================================================
-- SQL PORTFOLIO PROJECT: Grocery Store Sales Analysis
-- Purpose: Analyze grocery_store dataset to understand product performance, 
--          customer purchasing behavior, discount patterns, and revenue trends
-- Tools: MySQL / SQL Workbench
-- ====================================================================

-- Use the existing project database
USE sql_portfolio_projects;

-- 1. PROJECT OVERVIEW:
-- This project analyzes grocery store sales data to uncover insights about product performance, 
-- customer behavior, promotional effectiveness, and store revenue distribution. 
-- The goal is to support data-driven decisions for inventory management, marketing strategies, 
-- and overall store optimization.

-- 2. ANALYSIS PROBLEMS:

---------------------------------------------------------------------------------------------
-- 2.1: Which product-store combinations generate the highest average transaction value?
-- GOAL: Identify products and stores that contribute the most revenue per transaction.
---------------------------------------------------------------------------------------------
SELECT 
    store_name,
    product_name,
    ROUND(AVG(final_amount), 2) AS avg_transaction_value
FROM grocery_store2
GROUP BY store_name, product_name
ORDER BY avg_transaction_value DESC
LIMIT 5;

-- INSIGHT_1: 
-- The highest average transaction value is generated by the product "Apples" at the store "Megamart West Side". 
-- Other top-performing combinations include "Ground Beef" at "Corner Grocery", "Orange Juice" at "Greengrocer Plaza", etc.
-- This indicates that specific products in certain stores drive higher revenue per transaction.

-- RECOMMENDATION_1:
-- Focus marketing and inventory efforts on high-value products and stores. 
-- Consider targeted promotions, bundle offers, or loyalty incentives to maximize revenue and encourage repeat purchases.

---------------------------------------------------------------------------------------------
-- 2.2: What is the discount penetration across stores?
-- GOAL: Understand store discount strategies and evaluate promotional effectiveness.
---------------------------------------------------------------------------------------------
SELECT 
    store_name,
    ROUND(AVG(discount_amount), 2) AS avg_discount,
    COUNT(CASE WHEN discount_amount > 0 THEN 1 END) AS discounted_sales,
    COUNT(*) AS total_sales,
    ROUND((COUNT(CASE WHEN discount_amount > 0 THEN 1 END) / COUNT(*)) * 100, 2) AS discount_penetration_rate
FROM grocery_store2
GROUP BY store_name
ORDER BY avg_discount DESC;

-- INSIGHT_2:
-- QuickStop Market has 100% discount penetration, meaning every transaction included a discount. 
-- Other stores have lower penetration, showing varying discount strategies. 
-- This suggests QuickStop Market relies heavily on promotions to drive sales, while others are more selective.

-- RECOMMENDATION_2:
-- Evaluate the effectiveness of 100% discount strategies to ensure profitability. 
-- For stores with lower penetration, implement targeted promotions to increase engagement and repeat purchases without reducing margins.

---------------------------------------------------------------------------------------------
-- 2.3: Which products contribute most to customer loyalty?
-- GOAL: Identify products that incentivize repeat purchases and engagement.
---------------------------------------------------------------------------------------------
SELECT 
    product_name,
    ROUND(AVG(loyalty_points), 2) AS avg_points,
    MIN(loyalty_points) AS min_points,
    MAX(loyalty_points) AS max_points
FROM grocery_store2
GROUP BY product_name
ORDER BY avg_points DESC;

-- INSIGHT_3:
-- "Cereal" and "Yogurt" earn the highest loyalty points, indicating strong customer engagement. 
-- Customers tend to accumulate more points when purchasing these products.

-- RECOMMENDATION_3:
-- Promote high-loyalty products via loyalty programs, bundle offers, or campaigns. 
-- Introduce incentives for lower-loyalty products to boost overall engagement and drive traffic across categories.

---------------------------------------------------------------------------------------------
-- 2.4: How diverse is the product offering overall and per aisle?
-- GOAL: Evaluate product variety to ensure a balanced and attractive assortment.
---------------------------------------------------------------------------------------------
-- Total unique products
SELECT COUNT(DISTINCT product_name) AS unique_products
FROM grocery_store2;

-- Unique products per aisle
SELECT 
    aisle, 
    COUNT(DISTINCT product_name) AS num_products
FROM grocery_store2
GROUP BY aisle
ORDER BY num_products DESC;

-- INSIGHT_4:
-- "Bakery," "Beverages," and "Canned Soda" have the highest product diversity, each offering 18 unique products. 
-- This wide variety attracts customers and satisfies different preferences, while other aisles are less diverse.

-- RECOMMENDATION_4:
-- Expand product offerings in underrepresented aisles to balance assortment. 
-- Maintain high diversity in popular aisles, and review inventory and sales trends to optimize variety.

---------------------------------------------------------------------------------------------
-- 2.5: What is the geographic coverage of stores and revenue distribution?
-- GOAL: Understand revenue patterns by store location to identify high-performing regions and opportunities.
---------------------------------------------------------------------------------------------
-- Count of stores
SELECT COUNT(DISTINCT store_name) AS num_stores
FROM grocery_store2;

-- Total sales per store
SELECT 
    store_name, 
    SUM(final_amount) AS total_sales
FROM grocery_store2
GROUP BY store_name
ORDER BY total_sales DESC;

-- Average transaction value per store
SELECT 
    store_name, 
    ROUND(AVG(final_amount), 2) AS avg_transaction_value
FROM grocery_store2
GROUP BY store_name
ORDER BY avg_transaction_value DESC;

-- INSIGHT_5:
-- "Greengrocer Plaza," "Megamart Westside," and "Freshmart Downtown" are the top-performing stores, 
-- achieving the highest total sales and average transaction values, indicating strong customer traffic and revenue generation.

-- RECOMMENDATION_5:
-- Focus marketing, inventory, and staffing on high-performing stores to maximize revenue. 
-- Investigate low-performing stores for potential improvements and consider localized campaigns to boost sales.
