-- ====================================================================
-- SQL PORTFOLIO PROJECT: Grocery Stores Analysis
-- Purpose: Explore the grocery_store dataset to understand transaction
--          trends, discount effectiveness, customer loyalty behavior,
--          product diversity, and store-level performance.
-- Tools:   MySQL / SQL Workbench
-- ====================================================================

-- 1. PROJECT OVERVIEW:
-- This project analyzes retail transaction data from multiple grocery stores 
-- to understand sales performance, discount strategies, customer engagement,
-- product variety, and geographic revenue distribution.
-- The goal is to uncover meaningful insights that highlight revenue drivers, 
-- customer loyalty behavior, assortment strengths, and opportunities for 
-- operational improvement across the grocery retail network.
-- By exploring these patterns using SQL, the project supports data-driven
-- decisions in pricing, inventory, promotions, and store optimization.

-- 2. BUSINESS PROBLEMS:
-- 2.1: Which product + store combinations generate the highest average transaction value?
-- GOAL: Identify where revenue per transaction is strongest and understand what drives higher spending.

-- 2.2: How effective are store discount strategies, and which stores rely most on promotions?
-- GOAL: Measure discount penetration to assess promotional efficiency and sustainability.

-- 2.3: Which products drive the most customer loyalty based on points earned?
-- GOAL: Identify loyalty-boosting items that encourage repeat purchases.

-- 2.4: How diverse are product offerings overall and within each aisle?
-- GOAL: Evaluate assortment strength and identify aisles with expansion potential.

-- 2.5: Which store locations generate the highest total sales and highest average transaction values?
-- GOAL: Determine top-performing stores and find opportunities for strategic improvement.

USE sql_portfolio_projects;

-- View all available data
SELECT * FROM grocery_store2;

-- ====================================================================
-- 2.1 BUSINESS PROBLEM: Top 5 Average Transaction Values
-- ====================================================================
-- Goal: Identify stores and products generating the highest revenue per transaction.
-- Skills: GROUP BY, AVG, ROUND, ORDER BY, LIMIT
SELECT 
    store_name,
    product_name,
    ROUND(AVG(final_amount), 2) AS avg_transaction_value
FROM grocery_store2
GROUP BY store_name, product_name
ORDER BY avg_transaction_value DESC
LIMIT 5;

-- INSIGHT_1:
-- The highest average transaction value is generated by Apples at Megamart West Side.
-- Other top combinations include Ground Beef at Corner Grocery and Orange Juice at Greengrocer Plaza.
-- Certain product-store pairings significantly outperform others in driving revenue.

-- RECOMMENDATION_1:
-- Prioritize inventory, promotions, and visibility for high-value items like Apples at Megamart West Side.
-- Offer bundles or loyalty incentives around these products to maximize revenue and encourage repeat purchases.

-- ====================================================================
-- 2.2 BUSINESS PROBLEM: Discount Penetration
-- ====================================================================
-- Goal: Understand store discount strategies and promotional effectiveness.
-- Metrics:
-- - avg_discount: average discount per transaction
-- - discounted_sales: number of discounted transactions
-- - total_sales: total transactions
-- - discount_penetration_rate: % of transactions involving a discount
-- Skills: GROUP BY, CASE, COUNT, AVG, ROUND
SELECT 
    store_name,
    ROUND(AVG(discount_amount), 2) AS avg_discount,
    COUNT(CASE WHEN discount_amount > 0 THEN 1 END) AS discounted_sales,
    COUNT(*) AS total_sales,
    ROUND((COUNT(CASE WHEN discount_amount > 0 THEN 1 END) / COUNT(*)) * 100, 2) AS discount_penetration_rate
FROM grocery_store2
GROUP BY store_name
ORDER BY avg_discount DESC;

-- INSIGHT_2:
-- QuickStop Market shows a 100% discount penetration—every transaction included a discount.
-- Other stores show lower discount usage, indicating mixed promotional strategies.
-- This suggests QuickStop Market relies heavily on discount-driven sales.

-- RECOMMENDATION_2:
-- Reassess whether a 100% discount strategy at QuickStop Market is financially sustainable.
-- Stores with low penetration can test targeted promotions to raise customer engagement 
-- while protecting profit margins.

-- ====================================================================
-- 2.3 BUSINESS PROBLEM: Customer Loyalty
-- ====================================================================
-- Goal: Identify which products drive the most loyalty points.
-- Skills: GROUP BY, AVG, MIN, MAX, ROUND
SELECT 
    product_name,
    ROUND(AVG(loyalty_points), 2) AS avg_points,
    MIN(loyalty_points) AS min_points,
    MAX(loyalty_points) AS max_points
FROM grocery_store2
GROUP BY product_name
ORDER BY avg_points DESC;

-- INSIGHT_3:
-- Cereal and Yogurt earn the highest loyalty points, signaling their role in driving customer retention.
-- These items encourage repeat purchases and strengthen customer loyalty.

-- RECOMMENDATION_3:
-- Feature high-loyalty products like Cereal and Yogurt in promotions and loyalty programs.
-- Introduce incentives for lower-loyalty categories to improve overall customer engagement.

-- ====================================================================
-- 2.4 BUSINESS PROBLEM: Product Diversity
-- ====================================================================
-- Goal: Measure product variety overall and by aisle.
-- Skills: COUNT(DISTINCT), GROUP BY, ORDER BY

-- 4.1 Total unique products
SELECT COUNT(DISTINCT product_name) AS unique_products
FROM grocery_store2;

-- 4.2 Unique products per aisle
SELECT 
    aisle, 
    COUNT(DISTINCT product_name) AS num_products
FROM grocery_store2
GROUP BY aisle
ORDER BY num_products DESC;

-- INSIGHT_4:
-- Bakery, Beverages, and Canned Soda aisles each offer 18 unique products—the highest diversity.
-- These aisles provide wide choice and support higher customer satisfaction.
-- Other aisles might have limited selection.

-- RECOMMENDATION_4:
-- Expand offerings in aisles with low diversity to balance assortment.
-- Maintain high variety in strong aisles while optimizing underrepresented sections.

-- ====================================================================
-- 2.5 BUSINESS PROBLEM: Geographic Store Performance
-- ====================================================================
-- Goal: Analyze revenue performance by location.
-- Skills: SUM, AVG, GROUP BY, ROUND, ORDER BY

-- 5.1 Count of stores
SELECT COUNT(DISTINCT store_name) AS num_stores
FROM grocery_store2;

-- 5.2 Total sales per store
SELECT 
    store_name, 
    SUM(final_amount) AS total_sales
FROM grocery_store2
GROUP BY store_name
ORDER BY total_sales DESC;

-- 5.3 Average transaction value per store
SELECT 
    store_name, 
    ROUND(AVG(final_amount), 2) AS avg_transaction_value
FROM grocery_store2
GROUP BY store_name
ORDER BY avg_transaction_value DESC;

-- INSIGHT_5:
-- Greengrocer Plaza, Megamart Westside, and Freshmart Downtown lead in both total sales 
-- and average transaction value.
-- These stores generate strong traffic and revenue.

-- RECOMMENDATION_5:
-- Allocate more inventory, marketing, and staffing to top-performing stores.
-- Investigate reasons for low performance in other stores and introduce targeted improvements.
